name: Publish to Cognite Data Model

# Were we can define the inputs that our action will accept
inputs:
  clientId:
    required: true
  clientSecret:
    required: true
  cluster:
    required: true
  tenantId:
    required: false
  tokenUrl:
    required: false
  modelName:
    required: true
  modelFile:
    required: true
  modelDescription:
    required: false
  modelExternalId:
    required: false
  space:
    required: true
  project:
    required: true
  version:
    required: true

runs:
  using: 'docker'
  image: docker://cognite/datamodel-action:v1
